
Accuracy:  0.0
Traceback (most recent call last):
  File "run.py", line 132, in <module>
    train_loop()
  File "run.py", line 99, in train_loop
    wandb.log('loss: ', round(loss_per_1000.item(), 5))
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1543, in log
    self._log(data=data, step=step, commit=commit)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1329, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary
Traceback (most recent call last):
  File "run.py", line 132, in <module>
    train_loop()
  File "run.py", line 99, in train_loop
    wandb.log('loss: ', round(loss_per_1000.item(), 5))
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1543, in log
    self._log(data=data, step=step, commit=commit)
  File "/home3/ebrahim/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1329, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary
Batch number:  1000
Loss:  194.83942